version: '3.1'
services:
  dev-db:
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - test

networks:
  test:
